import type {
  OrderStatusResponse,
  QuoteResponse,
  SessionResolveResponse,
} from '@veyroxai/contracts';
import type { ResolvedMenu } from '../shared/menu-model.js';

const ID = {
  tenant: '3f1c0a11-0000-4000-8000-000000000001',
  menuV: '8a2e0b22-0000-4000-8000-000000000002',
  catHot: 'c1000000-0000-4000-8000-000000000010',
  catCold: 'c2000000-0000-4000-8000-000000000011',
  latte: '11000000-0000-4000-8000-000000000020',
  karkade: '12000000-0000-4000-8000-000000000021',
  cookie: '13000000-0000-4000-8000-000000000022',
  pudding: '14000000-0000-4000-8000-000000000023',
  gSize: '90000000-0000-4000-8000-000000000030',
  gMilk: '91000000-0000-4000-8000-000000000031',
  gExtras: '92000000-0000-4000-8000-000000000032',
  oRegular: 'a0000000-0000-4000-8000-000000000040',
  oLarge: 'a1000000-0000-4000-8000-000000000041',
  mWhole: 'b0000000-0000-4000-8000-000000000050',
  mOat: 'b1000000-0000-4000-8000-000000000051',
  mAlmond: 'b2000000-0000-4000-8000-000000000052',
  xShot: 'c0000000-0000-4000-8000-000000000060',
  xCinnamon: 'c1000000-0000-4000-8000-000000000061',
  xVanilla: 'c2000000-0000-4000-8000-000000000062',
};

export const sessionFixture: SessionResolveResponse = {
  tenant: {
    id: ID.tenant,
    name: 'Brew & Baladi',
    defaultLocale: 'en',
    supportedLocales: ['en', 'ar-EG'],
    currency: 'EGP',
    timezone: 'Africa/Cairo',
  },
  session: {
    menuVersion: ID.menuV,
    expiresAt: new Date(Date.now() + 15 * 60000).toISOString(),
    locale: 'en',
  },
  customer: {
    displayName: 'Karim',
    tier: 'silver',
    pointsBalance: 320,
    pointsToNextTier: 180,
    perks: ['free_alt_milk'],
  },
  store: { isOpen: true, closesAt: new Date(Date.now() + 5 * 3600000).toISOString() },
  ordering: { enabled: true, askTableNumber: false, minOrderValueMinor: 0, payAt: 'counter' },
  links: { menu: `/public/menu/${ID.menuV}`, availability: '/public/availability' },
  openOrder: null,
  traceId: 'dev-trace',
};

export const menuFixture: ResolvedMenu = {
  menuVersion: ID.menuV,
  staleAgainstVersion: false,
  optionAvailable: (id) => id !== ID.mAlmond,
  groupsById: new Map([
    [
      ID.gSize,
      {
        id: ID.gSize,
        name: { en: 'Size', 'ar-EG': 'الحجم' },
        selection: 'single',
        required: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          {
            id: ID.oRegular,
            name: { en: 'Regular', 'ar-EG': 'وسط' },
            priceDeltaMinor: 0,
            freeForTier: null,
            sort: 1,
          },
          {
            id: ID.oLarge,
            name: { en: 'Large', 'ar-EG': 'كبير' },
            priceDeltaMinor: 1500,
            freeForTier: null,
            sort: 2,
          },
        ],
      },
    ],
    [
      ID.gMilk,
      {
        id: ID.gMilk,
        name: { en: 'Milk', 'ar-EG': 'الحليب' },
        selection: 'single',
        required: true,
        minSelect: 1,
        maxSelect: 1,
        options: [
          {
            id: ID.mWhole,
            name: { en: 'Whole milk', 'ar-EG': 'كامل الدسم' },
            priceDeltaMinor: 0,
            freeForTier: null,
            sort: 1,
          },
          {
            id: ID.mOat,
            name: { en: 'Oat milk', 'ar-EG': 'شوفان' },
            priceDeltaMinor: 1200,
            freeForTier: 'silver',
            sort: 2,
          },
          {
            id: ID.mAlmond,
            name: { en: 'Almond milk', 'ar-EG': 'لوز' },
            priceDeltaMinor: 1200,
            freeForTier: 'silver',
            sort: 3,
          },
        ],
      },
    ],
    [
      ID.gExtras,
      {
        id: ID.gExtras,
        name: { en: 'Extras', 'ar-EG': 'إضافات' },
        selection: 'multi',
        required: false,
        minSelect: 0,
        maxSelect: 2,
        options: [
          {
            id: ID.xShot,
            name: { en: 'Extra shot', 'ar-EG': 'شوت إضافي' },
            priceDeltaMinor: 1000,
            freeForTier: null,
            sort: 1,
          },
          {
            id: ID.xCinnamon,
            name: { en: 'Cinnamon', 'ar-EG': 'قرفة' },
            priceDeltaMinor: 0,
            freeForTier: null,
            sort: 2,
          },
          {
            id: ID.xVanilla,
            name: { en: 'Vanilla', 'ar-EG': 'فانيليا' },
            priceDeltaMinor: 500,
            freeForTier: null,
            sort: 3,
          },
        ],
      },
    ],
  ]),
  categories: [
    {
      id: ID.catHot,
      sort: 1,
      name: { en: 'Hot drinks', 'ar-EG': 'مشروبات ساخنة' },
      items: [
        {
          id: ID.latte,
          sort: 1,
          name: { en: 'Cardamom Baladi Latte', 'ar-EG': 'لاتيه بلدي بالهيل' },
          description: {
            en: 'Double shot espresso, steamed milk, crushed green cardamom, clover honey.',
            'ar-EG': 'إسبريسو مزدوج، حليب مبخّر، هيل أخضر مطحون، وعسل نحل.',
          },
          basePriceMinor: 7000,
          prepSeconds: 150,
          imageUrl: null,
          modifierGroupIds: [ID.gSize, ID.gMilk, ID.gExtras],
          available: true,
          unavailableReason: null,
        },
        {
          id: ID.cookie,
          sort: 2,
          name: { en: 'Tahina Sea Salt Cookie', 'ar-EG': 'كوكيز الطحينة والملح' },
          description: { en: 'Soft sourdough cookie with sesame tahini and flaky sea salt.' },
          basePriceMinor: 4000,
          prepSeconds: 30,
          imageUrl: null,
          modifierGroupIds: [],
          available: true,
          unavailableReason: null,
        },
      ],
    },
    {
      id: ID.catCold,
      sort: 2,
      name: { en: 'Cold brew', 'ar-EG': 'كولد برو' },
      items: [
        {
          id: ID.karkade,
          sort: 1,
          name: { en: 'Cold Brew Hibiscus', 'ar-EG': 'كركديه كولد برو' },
          description: { en: '16h steeped Ethiopian single origin with Egyptian karkadeh.' },
          basePriceMinor: 6500,
          prepSeconds: 60,
          imageUrl: null,
          modifierGroupIds: [ID.gSize],
          available: true,
          unavailableReason: null,
        },
        {
          id: ID.pudding,
          sort: 2,
          name: { en: 'Baladi Date Bread Pudding', 'ar-EG': 'أم علي بالتمر البلدي' },
          description: { en: 'Warm brioche and Siwa dates with roasted pistachios.' },
          basePriceMinor: 5500,
          prepSeconds: 120,
          imageUrl: null,
          modifierGroupIds: [],
          available: false,
          unavailableReason: 'eighty_sixed',
        },
      ],
    },
  ],
};

export const quoteFixture: QuoteResponse = {
  lines: [
    {
      clientLineId: '0192d425-9790-7dd9-8aa9-8cbd4c3844d1',
      menuItemId: ID.latte,
      qty: 1,
      unitPriceMinor: 8500,
      modifierTotalMinor: 1500,
      lineTotalMinor: 8500,
      modifiers: [
        { id: ID.oLarge, priceDeltaMinor: 1500, waivedByTier: false },
        { id: ID.mOat, priceDeltaMinor: 1200, waivedByTier: true },
      ],
    },
    {
      clientLineId: '0192d425-9790-7dd9-8aa9-8cbd4c3844d2',
      menuItemId: ID.karkade,
      qty: 1,
      unitPriceMinor: 6500,
      modifierTotalMinor: 0,
      lineTotalMinor: 6500,
      modifiers: [],
    },
  ],
  subtotalMinor: 15000,
  discountMinor: 0,
  totalMinor: 15000,
  eta: { lowerMinutes: 8, upperMinutes: 12, queueDepth: 3 },
  loyalty: { pointsToEarn: 18, tier: 'silver', multiplier: 1.2 },
  unavailable: [],
  payAt: 'counter',
  traceId: 'dev-trace',
};

export const statusFixtures: Record<string, OrderStatusResponse> = {
  placed: {
    orderId: 'o_dev',
    orderNumber: 'A-27',
    statusLabel: { en: 'Sent to the kitchen', 'ar-EG': 'تم الإرسال للمطبخ' },
    totalMinor: 15000,
    payAt: 'counter',
    placedAt: new Date().toISOString(),
    traceId: 'dev',
    status: 'placed',
    eta: {
      lowerMinutes: 8,
      upperMinutes: 12,
      startsOnAccept: true,
      promisedLowerAt: null,
      promisedUpperAt: null,
    },
    loyalty: { pointsToEarn: 18 },
  },
  preparing: {
    orderId: 'o_dev',
    orderNumber: 'A-27',
    statusLabel: { en: 'Being prepared', 'ar-EG': 'جارٍ التحضير' },
    totalMinor: 15000,
    payAt: 'counter',
    placedAt: new Date().toISOString(),
    traceId: 'dev',
    status: 'preparing',
    acceptedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    eta: {
      lowerMinutes: 3,
      upperMinutes: 6,
      startsOnAccept: false,
      promisedLowerAt: new Date(Date.now() + 3 * 60000).toISOString(),
      promisedUpperAt: new Date(Date.now() + 6 * 60000).toISOString(),
    },
  },
  rejected: {
    orderId: 'o_dev',
    orderNumber: 'A-27',
    statusLabel: { en: 'Could not be prepared', 'ar-EG': 'تعذّر التحضير' },
    totalMinor: 15000,
    payAt: 'counter',
    placedAt: new Date().toISOString(),
    traceId: 'dev',
    status: 'rejected',
    rejectionReason: 'item_unavailable',
    rejectedAt: new Date().toISOString(),
  },
};
